version: '3.3'

services:
  dnscrypt-proxy:
    image: jedisct1/dnscrypt-proxy
    container_name: dnscrypt-proxy
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config:/config
    command: -config /config/dnscrypt-proxy.toml
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/53 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
