server_names = [
  'cloudflare',
  'cloudflare-ipv6',
  'google',
  'google-ipv6',
  'quad9-doh-ipv4-nofilter-ecs',
  'quad9-doh-ipv6-nofilter-ecs'
]

require_dnssec = true
require_nolog = true
require_nofilter = true
ignore_system_dns = true

bootstrap_resolvers = ['1.1.1.1:53', '9.9.9.10:53', '8.8.8.8:53']
fallback_resolvers = ['1.1.1.1:53', '8.8.8.8:53']

[ sources.'public-resolvers' ]
url = 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = 'public-resolvers.md'
refresh_delay = 72
